# Google Test

name: Google Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ master ]

jobs:
  google-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          sudo apt-get install -y cmake
          sudo apt-get install -y locales
          sudo locale-gen de_DE.UTF-8
          sudo apt-get install -y gcc git wget make libncurses-dev flex bison gperf python3 python3-pip python3-setuptools python3-serial python3-click python3-cryptography python3-future python3-pyparsing python3-pyelftools cmake ninja-build ccache libffi-dev libssl-dev

      - name: Install ESP-IDF v4.2.2
        run: |
          python --version
          mkdir ~/esp
          cd ~/esp
          git clone --recursive --branch v4.2.2 https://github.com/espressif/esp-idf.git
          cd esp-idf
          ./install.sh

      - name: Set up environment variables
        run: |
          echo "IDF_PATH=~/esp/esp-idf" >> $GITHUB_ENV
          echo "::add-path::~/esp/esp-idf/tools"

      - name: Build
        run: |
          . ~/esp/esp-idf/export.sh
          printenv | grep IDF
          idf.py version          
          cd tests
          mkdir cmake-build-unit-tests
          cd cmake-build-unit-tests
          cmake -G "Unix Makefiles" ..
          make -j 4
        
      - name: Run tests
        run: |
          cd tests/cmake-build-unit-tests
          ctest
