name: SonarCloud Analysis with Google Test and gcovr

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    env:
      BUILD_WRAPPER_OUT_DIR: bw-output # Directory where build-wrapper output will be placed

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
          submodules: true

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Check Python version
        run: |
          python --version
          python3 --version
          python3.8 --version

      - name: Set Python 3.8 as default
        run: |
          echo "alias python=python3.8" >> ~/.bashrc
          source ~/.bashrc          

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ cmake gcovr
          sudo apt-get install -y locales
          sudo locale-gen de_DE.UTF-8
          sudo apt-get install -y gcc git wget make libncurses-dev flex bison gperf python3 python3-pip python3-setuptools python3-serial python3-click python3-cryptography python3-future python3-pyparsing python3-pyelftools cmake ninja-build ccache libffi-dev libssl-dev

      - name: Install sonar-scanner and build-wrapper
        uses: SonarSource/sonarcloud-github-c-cpp@v1

      - name: Set IDF_PATH
        run: echo "IDF_PATH=${{ github.workspace }}/esp/esp-idf" >> $GITHUB_ENV

      - name: Cache ESP-IDF and tools
        id: cache-esp-idf
        uses: actions/cache@v3
        with:
          path: |
            ${GITHUB_WORKSPACE}/esp
            ${GITHUB_WORKSPACE}/.espressif
          key: esp-idf-${{ hashFiles('.github/workflows/sonar-scan.yml') }}
          restore-keys: esp-idf-

      - name: Download and install ESP-IDF v4.2.2
        if: steps.cache-esp-idf.outputs.cache-hit != 'true'
        run: |
          mkdir ${GITHUB_WORKSPACE}/esp
          cd ${GITHUB_WORKSPACE}/esp
          git clone --recursive --branch v4.2.2 https://github.com/espressif/esp-idf.git
          cd $IDF_PATH
          ./install.sh --python `which python3.8`

      - name: Run build-wrapper
        run: |
          source ${{ github.workspace }}/esp/esp-idf/export.sh
          python --version
          which python
          pip install bincopy
          printenv | grep IDF
          idf.py --version          
          mkdir build
          cd build
          build-wrapper-linux-x86-64 --out-dir ../${{ env.BUILD_WRAPPER_OUT_DIR }} cmake -DCMAKE_BUILD_TYPE=Debug ..
          build-wrapper-linux-x86-64 --out-dir ../${{ env.BUILD_WRAPPER_OUT_DIR }} make -j $(nproc)
          cd ..

      - name: Run test with coverage
        run: |
          cd tests
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="--coverage" ..
          make -j $(nproc)
          ctest
          cd ../..
          gcovr -r . --sonarqube -o coverage.xml

      - name: Run sonar-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner -X \
            --define sonar.cfamily.build-wrapper-output="${{ env.BUILD_WRAPPER_OUT_DIR }}" \
            --define sonar.coverageReportPaths=coverage.xml
